### ISSUE TITLE
Mudar o layout de 16:9 para 4:3

### ISSUE THREAD

**Issue by victordcsilva** [deuslirio/UFGTeX-Presentation#1]
Olá, tentei mudar o layout para 4:3, porém, acaba desconfigurando todo o layout, é possível utilizar 4:3 ou só foi feito para 16:9?

**Comment by deuslirio** [comment]
Olá, está em nossos planos oferecer uma versão 4:3, mas até o momento o design foi pensado apenas para o formato wide 16:9. Para definir 4:3 é necessário alterar também o formato das imagens em /lib/layouts e ajustar alguns espaçamentos e margens.
